version: "3.7"

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    networks:
      - optimus
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes: 
      - rabbitmq:/var/lib/rabbitmq
    
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    networks:
      - optimus
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=optimus
      - POSTGRES_PASSWORD=optimus
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  optimus:
    name: optimus

volumes:
  postgres:
    driver: local
  rabbitmq:
    driver: local
  
