version: "3.7"

services:
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - 5000:80
    networks:
      - optimus

  customers-service:
    image: customers
    container_name: customers-service
    restart: unless-stopped
    ports:
      - 5001:80
    networks:
      - optimus

  identity-service:
    image: identity
    container_name: identity-service
    restart: unless-stopped
    ports:
      - 5002:80
    networks:
      - optimus

networks:
  optimus:
    name: optimus
    external: true
