stages:
  - publish
  - deploy

variables:
  TAG_LATEST: registry2.kanakka.ir/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: registry2.kanakka.ir/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

publish:
  image: registry2.kanakka.ir/docker:20-dind
  stage: publish
  tags:
    - deployment
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]

  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login https://registry2.kanakka.ir -u $KANAKA_REGISTRY_USER -p $KANAKA_REGISTRY_PASS
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  only:
    - development
    - production

deploy:
  image: registry2.kanakka.ir/ssh-alpine
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login https://registry2.kanakka.ir -u $KANAKA_REGISTRY_USER -p $KANAKA_REGISTRY_PASS"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f customers-service || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 5003:80 --network=kanaka-network -e ASPNETCORE_ENVIRONMENT=Docker -e VIRTUAL_HOST=customerdev.kanakka.ir -e LETSENCRYPT_HOST=customerdev.kanakka.ir --name customers-service $TAG_COMMIT"
  only:
    - development
